### ISSUE TITLE
Link error 1120 while running `cargo install fltk-fluid` 

### ISSUE THREAD

**Issue by wellitecho** [fltk-rs/fluid#3]
# What I Did
cargo install fltk-fluid

Failed with 'error: linking with `link.exe` failed: exit code: 1120'

# OS Info
Rust: v1.58.1 stable-x86_64-pc-windows-msvc
Windows: win11
cmake:  version 3.22.1
git: version 2.34.1.windows.1

MSVC v142 - VS 2019 C++ x64/x86 build tools
Windows 10 SDK(10.0.19041.0)
also installed:
Windows 11 SDK(10.0.22000.0)
MSVC v141 - VS 2017 C++ x64/x86 build tools

# Full Backtrace
❯ cargo install fltk-fluid
    Updating `sjtu` index
  Installing fltk-fluid v0.1.6
   Compiling fltk-fluid v0.1.6
error: linking with `link.exe` failed: exit code: 1120
  |
  = note: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\link.exe" "/NOLOGO" "c:\\Users\\username\\cargo_target_dir\\release\\deps\\fltk_fluid-2120ebde4b691069.fltk_fluid.bf324184-cgu.0.rcgu.o" "c:\\Users\\username\\cargo_target_dir\\release\\deps\\fltk_fluid-2120ebde4b691069.fltk_fluid.bf324184-cgu.1.rcgu.o" "c:\\Users\\username\\cargo_target_dir\\release\\deps\\fltk_fluid-2120ebde4b691069.fltk_fluid.bf324184-cgu.10.rcgu.o" "c:\\Users\\username\\cargo_target_dir\\release\\deps\\fltk_fluid-2120ebde4b691069.fltk_fluid.bf324184-cgu.11.rcgu.o" "c:\\Users\\username\\cargo_target_dir\\release\\deps\\fltk_fluid-2120ebde4b691069.fltk_fluid.bf324184-cgu.12.rcgu.o" "c:\\Users\\username\\cargo_target_dir\\release\\deps\\fltk_fluid-2120ebde4b691069.fltk_fluid.bf324184-cgu.13.rcgu.o" "c:\\Users\\username\\cargo_target_dir\\release\\deps\\fltk_fluid-2120ebde4b691069.fltk_fluid.bf324184-cgu.14.rcgu.o" "c:\\Users\\username\\cargo_target_dir\\release\\deps\\fltk_fluid-2120ebde4b691069.fltk_fluid.bf324184-cgu.15.rcgu.o" "c:\\Users\\username\\cargo_target_dir\\release\\deps\\fltk_fluid-2120ebde4b691069.fltk_fluid.bf324184-cgu.2.rcgu.o" "c:\\Users\\username\\cargo_target_dir\\release\\deps\\fltk_fluid-2120ebde4b691069.fltk_fluid.bf324184-cgu.3.rcgu.o" "c:\\Users\\username\\cargo_target_dir\\release\\deps\\fltk_fluid-2120ebde4b691069.fltk_fluid.bf324184-cgu.4.rcgu.o" "c:\\Users\\username\\cargo_target_dir\\release\\deps\\fltk_fluid-2120ebde4b691069.fltk_fluid.bf324184-cgu.5.rcgu.o" "c:\\Users\\username\\cargo_target_dir\\release\\deps\\fltk_fluid-2120ebde4b691069.fltk_fluid.bf324184-cgu.6.rcgu.o" "c:\\Users\\username\\cargo_target_dir\\release\\deps\\fltk_fluid-2120ebde4b691069.fltk_fluid.bf324184-cgu.7.rcgu.o" "c:\\Users\\username\\cargo_target_dir\\release\\deps\\fltk_fluid-2120ebde4b691069.fltk_fluid.bf324184-cgu.8.rcgu.o" "c:\\Users\\username\\cargo_target_dir\\release\\deps\\fltk_fluid-2120ebde4b691069.fltk_fluid.bf324184-cgu.9.rcgu.o" "c:\\Users\\username\\cargo_target_dir\\release\\deps\\fltk_fluid-2120ebde4b691069.1t26u10gy4m8xjx1.rcgu.o" "/LIBPATH:c:\\Users\\username\\cargo_target_dir\\release\\deps" "/LIBPATH:c:\\Users\\username\\cargo_target_dir\\release\\build\\fltk-fluid-047f976afc335a5f\\out\\build" "/LIBPATH:c:\\Users\\username\\cargo_target_dir\\release\\build\\fltk-fluid-047f976afc335a5f\\out\\build\\Release" "/LIBPATH:c:\\Users\\username\\cargo_target_dir\\release\\build\\fltk-fluid-047f976afc335a5f\\out\\build\\lib" "/LIBPATH:c:\\Users\\username\\cargo_target_dir\\release\\build\\fltk-fluid-047f976afc335a5f\\out\\build\\lib\\Release" "/LIBPATH:c:\\Users\\username\\cargo_target_dir\\release\\build\\fltk-fluid-047f976afc335a5f\\out\\lib" "/LIBPATH:c:\\Users\\username\\cargo_target_dir\\release\\build\\fltk-fluid-047f976afc335a5f\\out\\lib64" "/LIBPATH:c:\\Users\\username\\cargo_target_dir\\release\\build\\fltk-fluid-047f976afc335a5f\\out\\lib\\Release" "/LIBPATH:c:\\Users\\username\\cargo_target_dir\\release\\build\\fltk-fluid-047f976afc335a5f\\out\\lib64\\Release" "/LIBPATH:C:\\Users\\username\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "/WHOLEARCHIVE:fltk.lib" "/WHOLEARCHIVE:fltk_images.lib" "/WHOLEARCHIVE:fltk_z.lib" "/WHOLEARCHIVE:fltk_jpeg.lib" "/WHOLEARCHIVE:fltk_png.lib" "/WHOLEARCHIVE:fltk_forms.lib" "/WHOLEARCHIVE:fluid.lib" "gdiplus.lib" "ws2_32.lib" "comctl32.lib" "gdi32.lib" "oleaut32.lib" "ole32.lib" "uuid.lib" "shell32.lib" "advapi32.lib" "comdlg32.lib" "winspool.lib" "user32.lib" "kernel32.lib" "odbc32.lib" "C:\\Users\\username\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd-77c29e3b2a96c9a6.rlib" "C:\\Users\\username\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libpanic_unwind-fac20c79897f2b3d.rlib" "C:\\Users\\username\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd_detect-a900fec85d21ec5f.rlib" "C:\\Users\\username\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_demangle-2803b5471132ab91.rlib" "C:\\Users\\username\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libhashbrown-bd7c3f8e84ab3746.rlib" "C:\\Users\\username\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_alloc-6353ac840b4a82ca.rlib" "C:\\Users\\username\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libunwind-8b22f250a6b6c0c3.rlib" "C:\\Users\\username\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcfg_if-837411c15bbbd755.rlib" "C:\\Users\\username\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liblibc-6e0180ba426c6f71.rlib" "C:\\Users\\username\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc-8fee164e10a5c1ee.rlib" "C:\\Users\\username\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_core-433995d9d73cd404.rlib" "C:\\Users\\username\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcore-d681750c6d1718a3.rlib" "C:\\Users\\username\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcompiler_builtins-fd343f19f347f62a.rlib" "kernel32.lib" "ws2_32.lib" "bcrypt.lib" "advapi32.lib" "userenv.lib" "kernel32.lib" "msvcrt.lib" "/NXCOMPAT" "/LIBPATH:C:\\Users\\username\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "/OUT:c:\\Users\\username\\cargo_target_dir\\release\\deps\\fltk_fluid-2120ebde4b691069.exe" "/OPT:REF,ICF" "/DEBUG" "/NATVIS:C:\\Users\\username\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:C:\\Users\\username\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\username\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/NATVIS:C:\\Users\\username\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libstd.natvis"
  = note: LINK : warning LNK4031: no subsystem specified; CONSOLE assumed
          fltk_images.lib(Fl_SVG_File_Surface.obj) : error LNK2019: unresolved external symbol png_create_write_struct referenced in function "protected: void __cdecl Fl_SVG_Graphics_Driver::define_rgb_png(class Fl_RGB_Image *,char const *,int,int)" (?define_rgb_png@Fl_SVG_Graphics_Driver@@IEAAXPEAVFl_RGB_Image@@PEBDHH@Z)
          fltk_images.lib(fl_write_png.obj) : error LNK2001: unresolved external symbol png_create_write_struct
          fltk_images.lib(Fl_SVG_File_Surface.obj) : error LNK2019: unresolved external symbol png_create_info_struct referenced in function "protected: void __cdecl Fl_SVG_Graphics_Driver::define_rgb_png(class Fl_RGB_Image *,char const *,int,int)" (?define_rgb_png@Fl_SVG_Graphics_Driver@@IEAAXPEAVFl_RGB_Image@@PEBDHH@Z)
          fltk_images.lib(Fl_PNG_Image.obj) : error LNK2001: unresolved external symbol png_create_info_struct
          fltk_images.lib(fl_write_png.obj) : error LNK2001: unresolved external symbol png_create_info_struct
          fltk_images.lib(Fl_SVG_File_Surface.obj) : error LNK2019: unresolved external symbol png_write_end referenced in function "protected: void __cdecl Fl_SVG_Graphics_Driver::define_rgb_png(class Fl_RGB_Image *,char const *,int,int)" (?define_rgb_png@Fl_SVG_Graphics_Driver@@IEAAXPEAVFl_RGB_Image@@PEBDHH@Z)
          fltk_images.lib(fl_write_png.obj) : error LNK2001: unresolved external symbol png_write_end
          fltk_images.lib(Fl_SVG_File_Surface.obj) : error LNK2019: unresolved external symbol png_destroy_write_struct referenced in function "protected: void __cdecl Fl_SVG_Graphics_Driver::define_rgb_png(class Fl_RGB_Image *,char const *,int,int)" (?define_rgb_png@Fl_SVG_Graphics_Driver@@IEAAXPEAVFl_RGB_Image@@PEBDHH@Z)
          fltk_images.lib(fl_write_png.obj) : error LNK2001: unresolved external symbol png_destroy_write_struct
          fltk_images.lib(Fl_SVG_File_Surface.obj) : error LNK2019: unresolved external symbol png_set_write_fn referenced in function "protected: void __cdecl Fl_SVG_Graphics_Driver::define_rgb_png(class Fl_RGB_Image *,char const *,int,int)" (?define_rgb_png@Fl_SVG_Graphics_Driver@@IEAAXPEAVFl_RGB_Image@@PEBDHH@Z)
          fltk_images.lib(Fl_SVG_File_Surface.obj) : error LNK2019: unresolved external symbol png_get_io_ptr referenced in function "protected: void __cdecl Fl_SVG_Graphics_Driver::define_rgb_png(class Fl_RGB_Image *,char const *,int,int)" (?define_rgb_png@Fl_SVG_Graphics_Driver@@IEAAXPEAVFl_RGB_Image@@PEBDHH@Z)
          fltk_images.lib(Fl_PNG_Image.obj) : error LNK2001: unresolved external symbol png_get_io_ptr
          fltk_images.lib(Fl_SVG_File_Surface.obj) : error LNK2019: unresolved external symbol png_set_rows referenced in function "protected: void __cdecl Fl_SVG_Graphics_Driver::define_rgb_png(class Fl_RGB_Image *,char const *,int,int)" (?define_rgb_png@Fl_SVG_Graphics_Driver@@IEAAXPEAVFl_RGB_Image@@PEBDHH@Z)
          fltk_images.lib(Fl_SVG_File_Surface.obj) : error LNK2019: unresolved external symbol png_set_IHDR referenced in function "protected: void __cdecl Fl_SVG_Graphics_Driver::define_rgb_png(class Fl_RGB_Image *,char const *,int,int)" (?define_rgb_png@Fl_SVG_Graphics_Driver@@IEAAXPEAVFl_RGB_Image@@PEBDHH@Z)
          fltk_images.lib(fl_write_png.obj) : error LNK2001: unresolved external symbol png_set_IHDR
          fltk_images.lib(Fl_SVG_File_Surface.obj) : error LNK2019: unresolved external symbol png_write_png referenced in function "protected: void __cdecl Fl_SVG_Graphics_Driver::define_rgb_png(class Fl_RGB_Image *,char const *,int,int)" (?define_rgb_png@Fl_SVG_Graphics_Driver@@IEAAXPEAVFl_RGB_Image@@PEBDHH@Z)
          fltk_images.lib(Fl_SVG_File_Surface.obj) : error LNK2019: unresolved external symbol jpeg_std_error referenced in function "protected: void __cdecl Fl_SVG_Graphics_Driver::define_rgb_jpeg(class Fl_RGB_Image *,char const *,int,int)" (?define_rgb_jpeg@Fl_SVG_Graphics_Driver@@IEAAXPEAVFl_RGB_Image@@PEBDHH@Z)
          fltk_images.lib(Fl_JPEG_Image.obj) : error LNK2001: unresolved external symbol jpeg_std_error
          fltk_images.lib(Fl_SVG_File_Surface.obj) : error LNK2019: unresolved external symbol jpeg_CreateCompress referenced in function "protected: void __cdecl Fl_SVG_Graphics_Driver::define_rgb_jpeg(class Fl_RGB_Image *,char const *,int,int)" (?define_rgb_jpeg@Fl_SVG_Graphics_Driver@@IEAAXPEAVFl_RGB_Image@@PEBDHH@Z)
          fltk_images.lib(Fl_SVG_File_Surface.obj) : error LNK2019: unresolved external symbol jpeg_destroy_compress referenced in function "protected: void __cdecl Fl_SVG_Graphics_Driver::define_rgb_jpeg(class Fl_RGB_Image *,char const *,int,int)" (?define_rgb_jpeg@Fl_SVG_Graphics_Driver@@IEAAXPEAVFl_RGB_Image@@PEBDHH@Z)
          fltk_images.lib(Fl_SVG_File_Surface.obj) : error LNK2019: unresolved external symbol jpeg_set_defaults referenced in function "protected: void __cdecl Fl_SVG_Graphics_Driver::define_rgb_jpeg(class Fl_RGB_Image *,char const *,int,int)" (?define_rgb_jpeg@Fl_SVG_Graphics_Driver@@IEAAXPEAVFl_RGB_Image@@PEBDHH@Z)
          fltk_images.lib(Fl_SVG_File_Surface.obj) : error LNK2019: unresolved external symbol jpeg_start_compress referenced in function "protected: void __cdecl Fl_SVG_Graphics_Driver::define_rgb_jpeg(class Fl_RGB_Image *,char const *,int,int)" (?define_rgb_jpeg@Fl_SVG_Graphics_Driver@@IEAAXPEAVFl_RGB_Image@@PEBDHH@Z)
          fltk_images.lib(Fl_SVG_File_Surface.obj) : error LNK2019: unresolved external symbol jpeg_write_scanlines referenced in function "protected: void __cdecl Fl_SVG_Graphics_Driver::define_rgb_jpeg(class Fl_RGB_Image *,char const *,int,int)" (?define_rgb_jpeg@Fl_SVG_Graphics_Driver@@IEAAXPEAVFl_RGB_Image@@PEBDHH@Z)
          fltk_images.lib(Fl_SVG_File_Surface.obj) : error LNK2019: unresolved external symbol jpeg_finish_compress referenced in function "protected: void __cdecl Fl_SVG_Graphics_Driver::define_rgb_jpeg(class Fl_RGB_Image *,char const *,int,int)" (?define_rgb_jpeg@Fl_SVG_Graphics_Driver@@IEAAXPEAVFl_RGB_Image@@PEBDHH@Z)
          fltk_images.lib(Fl_SVG_Image.obj) : error LNK2019: unresolved external symbol gzdopen referenced in function "char * __cdecl svg_inflate(char const *)" (?svg_inflate@@YAPEADPEBD@Z)
          fltk_images.lib(fl_images_core.obj) : error LNK2001: unresolved external symbol gzdopen
          fltk_images.lib(Fl_SVG_Image.obj) : error LNK2019: unresolved external symbol gzread referenced in function "char * __cdecl svg_inflate(char const *)" (?svg_inflate@@YAPEADPEBD@Z)
          fltk_images.lib(fl_images_core.obj) : error LNK2001: unresolved external symbol gzread
          fltk_images.lib(Fl_SVG_Image.obj) : error LNK2019: unresolved external symbol gzclose referenced in function "char * __cdecl svg_inflate(char const *)" (?svg_inflate@@YAPEADPEBD@Z)
          fltk_images.lib(fl_images_core.obj) : error LNK2001: unresolved external symbol gzclose
          fltk_images.lib(Fl_PNG_Image.obj) : error LNK2019: unresolved external symbol png_create_read_struct referenced in function "private: void __cdecl Fl_PNG_Image::load_png_(char const *,unsigned char const *,int)" (?load_png_@Fl_PNG_Image@@AEAAXPEBDPEBEH@Z)
          fltk_images.lib(Fl_PNG_Image.obj) : error LNK2019: unresolved external symbol png_set_longjmp_fn referenced in function "private: void __cdecl Fl_PNG_Image::load_png_(char const *,unsigned char const *,int)" (?load_png_@Fl_PNG_Image@@AEAAXPEBDPEBEH@Z)
          fltk_images.lib(Fl_PNG_Image.obj) : error LNK2019: unresolved external symbol png_read_info referenced in function "private: void __cdecl Fl_PNG_Image::load_png_(char const *,unsigned char const *,int)" (?load_png_@Fl_PNG_Image@@AEAAXPEBDPEBEH@Z)
          fltk_images.lib(Fl_PNG_Image.obj) : error LNK2019: unresolved external symbol png_set_expand referenced in function "private: void __cdecl Fl_PNG_Image::load_png_(char const *,unsigned char const *,int)" (?load_png_@Fl_PNG_Image@@AEAAXPEBDPEBEH@Z)
          fltk_images.lib(Fl_PNG_Image.obj) : error LNK2019: unresolved external symbol png_set_tRNS_to_alpha referenced in function "private: void __cdecl Fl_PNG_Image::load_png_(char const *,unsigned char const *,int)" (?load_png_@Fl_PNG_Image@@AEAAXPEBDPEBEH@Z)
          fltk_images.lib(Fl_PNG_Image.obj) : error LNK2019: unresolved external symbol png_set_packing referenced in function "private: void __cdecl Fl_PNG_Image::load_png_(char const *,unsigned char const *,int)" (?load_png_@Fl_PNG_Image@@AEAAXPEBDPEBEH@Z)
          fltk_images.lib(Fl_PNG_Image.obj) : error LNK2019: unresolved external symbol png_set_interlace_handling referenced in function "private: void __cdecl Fl_PNG_Image::load_png_(char const *,unsigned char const *,int)" (?load_png_@Fl_PNG_Image@@AEAAXPEBDPEBEH@Z)
          fltk_images.lib(Fl_PNG_Image.obj) : error LNK2019: unresolved external symbol png_set_strip_16 referenced in function "private: void __cdecl Fl_PNG_Image::load_png_(char const *,unsigned char const *,int)" (?load_png_@Fl_PNG_Image@@AEAAXPEBDPEBEH@Z)
          fltk_images.lib(Fl_PNG_Image.obj) : error LNK2019: unresolved external symbol png_read_rows referenced in function "private: void __cdecl Fl_PNG_Image::load_png_(char const *,unsigned char const *,int)" (?load_png_@Fl_PNG_Image@@AEAAXPEBDPEBEH@Z)
          fltk_images.lib(Fl_PNG_Image.obj) : error LNK2019: unresolved external symbol png_read_end referenced in function "private: void __cdecl Fl_PNG_Image::load_png_(char const *,unsigned char const *,int)" (?load_png_@Fl_PNG_Image@@AEAAXPEBDPEBEH@Z)
          fltk_images.lib(Fl_PNG_Image.obj) : error LNK2019: unresolved external symbol png_destroy_read_struct referenced in function "private: void __cdecl Fl_PNG_Image::load_png_(char const *,unsigned char const *,int)" (?load_png_@Fl_PNG_Image@@AEAAXPEBDPEBEH@Z)
          fltk_images.lib(Fl_PNG_Image.obj) : error LNK2019: unresolved external symbol png_init_io referenced in function "private: void __cdecl Fl_PNG_Image::load_png_(char const *,unsigned char const *,int)" (?load_png_@Fl_PNG_Image@@AEAAXPEBDPEBEH@Z)
          fltk_images.lib(fl_write_png.obj) : error LNK2001: unresolved external symbol png_init_io
          fltk_images.lib(Fl_PNG_Image.obj) : error LNK2019: unresolved external symbol png_set_read_fn referenced in function "private: void __cdecl Fl_PNG_Image::load_png_(char const *,unsigned char const *,int)" (?load_png_@Fl_PNG_Image@@AEAAXPEBDPEBEH@Z)
          fltk_images.lib(Fl_PNG_Image.obj) : error LNK2019: unresolved external symbol png_error referenced in function png_read_data_from_mem
          fltk_images.lib(Fl_PNG_Image.obj) : error LNK2019: unresolved external symbol png_get_valid referenced in function "private: void __cdecl Fl_PNG_Image::load_png_(char const *,unsigned char const *,int)" (?load_png_@Fl_PNG_Image@@AEAAXPEBDPEBEH@Z)
          fltk_images.lib(Fl_PNG_Image.obj) : error LNK2019: unresolved external symbol png_get_image_width referenced in function "private: void __cdecl Fl_PNG_Image::load_png_(char const *,unsigned char const *,int)" (?load_png_@Fl_PNG_Image@@AEAAXPEBDPEBEH@Z)
          fltk_images.lib(Fl_PNG_Image.obj) : error LNK2019: unresolved external symbol png_get_image_height referenced in function "private: void __cdecl Fl_PNG_Image::load_png_(char const *,unsigned char const *,int)" (?load_png_@Fl_PNG_Image@@AEAAXPEBDPEBEH@Z)
          fltk_images.lib(Fl_PNG_Image.obj) : error LNK2019: unresolved external symbol png_get_bit_depth referenced in function "private: void __cdecl Fl_PNG_Image::load_png_(char const *,unsigned char const *,int)" (?load_png_@Fl_PNG_Image@@AEAAXPEBDPEBEH@Z)
          fltk_images.lib(Fl_PNG_Image.obj) : error LNK2019: unresolved external symbol png_get_color_type referenced in function "private: void __cdecl Fl_PNG_Image::load_png_(char const *,unsigned char const *,int)" (?load_png_@Fl_PNG_Image@@AEAAXPEBDPEBEH@Z)
          fltk_images.lib(Fl_PNG_Image.obj) : error LNK2019: unresolved external symbol png_get_tRNS referenced in function "private: void __cdecl Fl_PNG_Image::load_png_(char const *,unsigned char const *,int)" (?load_png_@Fl_PNG_Image@@AEAAXPEBDPEBEH@Z)
          fltk_images.lib(Fl_JPEG_Image.obj) : error LNK2019: unresolved external symbol jpeg_CreateDecompress referenced in function "protected: void __cdecl Fl_JPEG_Image::load_jpg_(char const *,char const *,unsigned char const *)" (?load_jpg_@Fl_JPEG_Image@@IEAAXPEBD0PEBE@Z)
          fltk_images.lib(Fl_JPEG_Image.obj) : error LNK2019: unresolved external symbol jpeg_destroy_decompress referenced in function "protected: void __cdecl Fl_JPEG_Image::load_jpg_(char const *,char const *,unsigned char const *)" (?load_jpg_@Fl_JPEG_Image@@IEAAXPEBD0PEBE@Z)
          fltk_images.lib(Fl_JPEG_Image.obj) : error LNK2019: unresolved external symbol jpeg_stdio_src referenced in function "protected: void __cdecl Fl_JPEG_Image::load_jpg_(char const *,char const *,unsigned char const *)" (?load_jpg_@Fl_JPEG_Image@@IEAAXPEBD0PEBE@Z)
          fltk_images.lib(Fl_JPEG_Image.obj) : error LNK2019: unresolved external symbol jpeg_read_header referenced in function "protected: void __cdecl Fl_JPEG_Image::load_jpg_(char const *,char const *,unsigned char const *)" (?load_jpg_@Fl_JPEG_Image@@IEAAXPEBD0PEBE@Z)
          fltk_images.lib(Fl_JPEG_Image.obj) : error LNK2019: unresolved external symbol jpeg_start_decompress referenced in function "protected: void __cdecl Fl_JPEG_Image::load_jpg_(char const *,char const *,unsigned char const *)" (?load_jpg_@Fl_JPEG_Image@@IEAAXPEBD0PEBE@Z)
          fltk_images.lib(Fl_JPEG_Image.obj) : error LNK2019: unresolved external symbol jpeg_read_scanlines referenced in function "protected: void __cdecl Fl_JPEG_Image::load_jpg_(char const *,char const *,unsigned char const *)" (?load_jpg_@Fl_JPEG_Image@@IEAAXPEBD0PEBE@Z)
          fltk_images.lib(Fl_JPEG_Image.obj) : error LNK2019: unresolved external symbol jpeg_finish_decompress referenced in function "protected: void __cdecl Fl_JPEG_Image::load_jpg_(char const *,char const *,unsigned char const *)" (?load_jpg_@Fl_JPEG_Image@@IEAAXPEBD0PEBE@Z)
          fltk_images.lib(Fl_JPEG_Image.obj) : error LNK2019: unresolved external symbol jpeg_calc_output_dimensions referenced in function "protected: void __cdecl Fl_JPEG_Image::load_jpg_(char const *,char const *,unsigned char const *)" (?load_jpg_@Fl_JPEG_Image@@IEAAXPEBD0PEBE@Z)
          fltk_images.lib(Fl_JPEG_Image.obj) : error LNK2019: unresolved external symbol jpeg_resync_to_restart referenced in function "protected: void __cdecl Fl_JPEG_Image::load_jpg_(char const *,char const *,unsigned char const *)" (?load_jpg_@Fl_JPEG_Image@@IEAAXPEBD0PEBE@Z)
          fltk_images.lib(fl_write_png.obj) : error LNK2019: unresolved external symbol png_write_info referenced in function "int __cdecl fl_write_png(char const *,char const *,int,int,int,int)" (?fl_write_png@@YAHPEBD0HHHH@Z)
          fltk_images.lib(fl_write_png.obj) : error LNK2019: unresolved external symbol png_write_row referenced in function "int __cdecl fl_write_png(char const *,char const *,int,int,int,int)" (?fl_write_png@@YAHPEBD0HHHH@Z)
          fltk_images.lib(fl_write_png.obj) : error LNK2019: unresolved external symbol png_set_sRGB referenced in function "int __cdecl fl_write_png(char const *,char const *,int,int,int,int)" (?fl_write_png@@YAHPEBD0HHHH@Z)
          fltk_png.lib(pngwutil.obj) : error LNK2019: unresolved external symbol deflate referenced in function fltk_png_compress_IDAT
          fltk_png.lib(pngwutil.obj) : error LNK2019: unresolved external symbol deflateEnd referenced in function png_deflate_claim
          fltk_png.lib(pngwrite.obj) : error LNK2001: unresolved external symbol deflateEnd
          fltk_png.lib(pngwutil.obj) : error LNK2019: unresolved external symbol deflateReset referenced in function png_deflate_claim
          fltk_png.lib(pngwutil.obj) : error LNK2019: unresolved external symbol deflateInit2_ referenced in function png_deflate_claim
          fltk_png.lib(pngrutil.obj) : error LNK2019: unresolved external symbol inflate referenced in function fltk_png_read_IDAT_data
          fltk_png.lib(pngrutil.obj) : error LNK2019: unresolved external symbol inflateReset referenced in function png_decompress_chunk
          fltk_png.lib(png.obj) : error LNK2001: unresolved external symbol inflateReset
          fltk_png.lib(pngrutil.obj) : error LNK2019: unresolved external symbol inflateReset2 referenced in function png_inflate_claim
          fltk_png.lib(pngrutil.obj) : error LNK2019: unresolved external symbol inflateInit2_ referenced in function png_inflate_claim
          fltk_png.lib(pngrutil.obj) : error LNK2019: unresolved external symbol inflateValidate referenced in function png_inflate_claim
          fltk_png.lib(pngread.obj) : error LNK2019: unresolved external symbol inflateEnd referenced in function fltk_png_destroy_read_struct
          fltk_png.lib(png.obj) : error LNK2019: unresolved external symbol adler32 referenced in function png_compare_ICC_profile_with_sRGB
          fltk_png.lib(png.obj) : error LNK2019: unresolved external symbol crc32 referenced in function fltk_png_calculate_crc
          c:\Users\username\cargo_target_dir\release\deps\fltk_fluid-2120ebde4b691069.exe : fatal error LNK1120: 63 unresolved externals

error: failed to compile `fltk-fluid v0.1.6`, intermediate artifacts can be found at `c:\Users\username\cargo_target_dir\`

Caused by:
  could not compile `fltk-fluid` due to previous error

**Comment by MoAlyousef** [comment]
It could be a windows 11 thing. I can't reproduce in [CI](https://github.com/MoAlyousef/test-fltk-fluid/runs/4896409596?check_suite_focus=true).

nor locally:
![fltk-fluid](https://user-images.githubusercontent.com/37966791/150529652-a188ba20-d1d5-4105-800a-4e28bc91bbb3.jpg)

Can you try running the install from a native tools command prompt (it should appear once you start typing "native" in the start menu).

**Comment by wellitecho** [comment]
Tried it in native tools command prompt, and it failed with the same error: linking with `link.exe` failed: exit code: 1120.
Maybe it's win11.

**Comment by MoAlyousef** [comment]
I'm not sure how to debug this. But if you have a project that uses fltk-rs, fluid is automatically built during the build process of FLTK. The binary can usually be found in ./target/debug/build/fltk-sys-<some_hash>/out/bin/fluid. You can copy the fluid binary into %HOME%/.cargo/bin

So this could work as a workaround.

**Comment by wellitecho** [comment]
Thanks. fluid binary is found at said path.
One thing that could be related to this is that I can build fltk-rs only with feature 'fltk-bundled' enabled.
