### ISSUE TITLE
Windows 10 failed to run a custom build command

### ISSUE THREAD

**Issue by ByteStardust** [fltk-rs/fluid#5]
OS 
Windows 10 Enterprise LTSC

cargo 1.72.1 (103a7ff2e 2023-08-15)
release: 1.72.1
commit-hash: 103a7ff2ee7678d34f34d778614c5eb2525ae9de
commit-date: 2023-08-15
host: x86_64-pc-windows-msvc
libgit2: 1.6.4 (sys:0.17.2 vendored)
libcurl: 8.1.2-DEV (sys:0.4.63+curl-8.1.2 vendored ssl:Schannel)
os: Windows 10.0.19044 (Windows 10 Enterprise LTSC 2021) [64-bit]

Error:
cargo install fltk-fluid
    Updating crates.io index
  Installing fltk-fluid v0.1.9
    Updating crates.io index
   Compiling cc v1.0.83
   Compiling cmake v0.1.50
   Compiling fltk-fluid v0.1.9
error: failed to run custom build command for `fltk-fluid v0.1.9`

Caused by:
  process didn't exit successfully: `C:\Users\admin\.cargo\bin\release\build\fltk-fluid-ba221c03046df901\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs

  --- stderr
  thread 'main' panicked at 'Git is needed to retrieve the fltk source files!: Error { kind: NotFound, message: "program not found" }', C:\Users\admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\fltk-fluid-0.1.9\build.rs:15:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: failed to compile `fltk-fluid v0.1.9`, intermediate artifacts can be found at `C:\Users\admin\.cargo\bin`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

config.toml
[env]
CARGO_TARGET_DIR = 'C:\Users\admin\.cargo\bin'

[build]
target-dir = 'C:\Users\admin\.cargo\bin'

**Comment by MoAlyousef** [comment]
This builds fluid from source, so you will need Git, CMake and the msvc compiler.

**Comment by ByteStardust** [comment]
cmake and msvc are available, do I need to install git again?

**Comment by ByteStardust** [comment]
Installing git again after installation has been resolved
