### ISSUE TITLE
Update fluid to fltk 1.5?

### ISSUE THREAD

**Issue by AllenDang** [fltk-rs/fluid#6]
I'm ready like to use fluid to design the GUI, is it possible to upgrade this tool to fltk 1.5?

**Comment by MoAlyousef** [comment]
I’ll have to update fluid to use the latest fltk sources, but currently fluid already uses fltk 1.4 abi.

**Comment by AllenDang** [comment]
@MoAlyousef I just want to use grid directly from fluid, it will be great if this crate could be updated.

**Comment by AllenDang** [comment]
@MoAlyousef My mistake, should be update fluid to fltk 1.5 in this case.

**Comment by MoAlyousef** [comment]
I've just published a new version, if you can try it out. You might have to run `cargo uninstall fltk-fluid` first.

**Comment by AllenDang** [comment]
@MoAlyousef Thanks very much! It works!
